# -*- coding: utf-8 -*-
"""Task1_LGMVIP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bO0q7RWy6WGP26Gzxc7RvIMzVKWEz77j

***LGMVIP***

**DATA SCIENCE INTERNSHIP**

**TASK 1 | IRIS FLOWER CLASSIFICATION**

Importing Libararies
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

"""Reading Data from CSV File"""

columns = ['Sepal length','Sepal width','Petal length','Petal width','class_labels']
data=pd.read_csv('iris.data', names=columns)
data.head()

"""Plotting Data for Graphical Representation"""

sns.pairplot(data,hue="class_labels")

data2=data.values

X=data2[:,0:4]
Y=data2[:,4]

"""Trimming Data"""

from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

"""*Model 1: SVC*"""

from sklearn.svm import SVC
model_svc=SVC()
model_svc.fit(x_train,y_train)

prediction1=model_svc.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction1)*100)

"""*Model 2: LogisticRegression*"""

from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(x_train,y_train)

prediction2=model_LR.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction2)*100)

"""*Model 3: DecisionTreeClassifier*"""

from sklearn.tree import DecisionTreeClassifier
model_DTC=DecisionTreeClassifier()
model_DTC.fit(x_train,y_train)

prediction3=model_DTC.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction3)*100)

"""Classification Report"""

from sklearn.metrics import classification_report
print(classification_report(y_test, prediction3))

"""

---


Test Sample

---

"""

x_newarray=np.array([[3.4,1.2,2.2,5.2],[5.5,3.3,2.4,1.8],[4.1,3.2,2.2,3.6]])
newprediction=model_svc.predict(x_newarray)
print("The Iris Speice is: {}".format(newprediction))